#ifndef BW_GRAPH_DB_DB_H
#define BW_GRAPH_DB_DB_H

#include "bw_graph/buf/buf_pool.h"
#include "bw_graph/buf/csr_flusher.h"
#include "bw_graph/buf/delta_flusher.h"
#include "bw_graph/buf/page_map.h"
#include "bw_graph/buf/sketch.h"
#include "bw_graph/common/type.h"
#include "bw_graph/db/external.h"
#include "bw_graph/db/property_store.h"
#include "bw_graph/index/vertex_index.h"
#include "bw_graph/io/io_csr.h"
#include "bw_graph/io/io_delta.h"
#include "bw_graph/io/io_index.h"
#include "bw_graph/mem/mem_g0com.h"
#include "bw_graph/mem/mem_g0map.h"
#include "bw_graph/part/smo.h"
#include "bw_graph/storage/disk_manager.h"

#if defined(BW_GRAPH_ENABLE_TRANSACTION)
#include "bw_graph/db/txn.h"
#endif // BW_GRAPH_ENABLE_TRANSACTION

#include <cstddef>
#include <cstdint>
#include <folly/container/F14Set.h>
#include <memory>
#include <mutex>
#include <optional>
#include <rocksdb/db.h>
#include <rocksdb/options.h>
#include <rocksdb/table.h>
#include <rocksdb/write_batch.h>
#include <string>
#include <sys/types.h>
#include <tbb/blocked_range.h>
#include <tbb/concurrent_hash_map.h>
#include <tbb/concurrent_queue.h>
#include <tbb/concurrent_vector.h>
#include <tbb/parallel_for.h>
#include <tbb/parallel_reduce.h>
#include <tbb/task_arena.h>
#include <tbb/task_group.h>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <yaml-cpp/yaml.h>

/**
 * @brief Thread-local data structures - simplified to store only necessary info
 */
struct segment_result_t {
  /**
   * @brief CSR pages generated by this segment
   */
  std::vector<csr_page_t*> pages;

  /**
   * @brief Giant vertex IDs in this segment
   */
  std::vector<v_id_t> giant_vertices;

  /**
   * @brief Normal vertex metadata: (vertex_id, local_page_no, offset)
   */
  std::vector<std::tuple<v_id_t, page_no_t, uint16_t>> normal_vertices;
};

/**
 * @brief Result structure for TAT (Topology-Aware Tree) build operations
 *
 * Contains all necessary information about a built TAT including the root page,
 * hierarchy metadata, and page mappings for navigation.
 */
struct tat_build_result_t {
  /**
   * @brief Pointer to the root page of the TAT
   */
  index_page_t* root_page;

  /**
   * @brief Number of levels in the TAT hierarchy
   */
  uint32_t level_count;

  /**
   * @brief Page number of the root page (highest page number used)
   */
  page_no_t root_page_no;

  /**
   * @brief Map from page number to index page pointer for all index pages in
   * the TAT
   */
  folly::F14FastMap<page_no_t, index_page_t*> index_pages;

  /**
   * @brief Minimum index page number used (for reverse allocation)
   *
   * When allocating from high to low, this is the smallest page number used.
   * Next TAT should start from (min_index_page_no - 1)
   */
  page_no_t next_index_page_no;
};

/**
 * @brief Stable pointer to one delta record.
 *
 * Delta records live inside delta pages and are addressed by page number plus
 * record index. This avoids exposing raw pointers that may become invalid when
 * the buffer pool evicts or reloads a page.
 */
struct delta_record_ptr_t {
  page_no_t page_no{INVALID_DELTA_PAGE_NO};
  uint32_t record_idx{INVALID_DELTA_RECORD_IDX};

  delta_record_ptr_t() = default;

  delta_record_ptr_t(page_no_t page_no, uint32_t record_idx)
      : page_no(page_no), record_idx(record_idx) {}

  explicit delta_record_ptr_t(delta_head_t head)
      : page_no(head.page_no), record_idx(head.record_idx) {}

  bool is_valid() const {
    return page_no != INVALID_DELTA_PAGE_NO && record_idx != INVALID_DELTA_RECORD_IDX;
  }

  static delta_record_ptr_t invalid() { return delta_record_ptr_t{}; }
};

using read_neighbor_with_delta_result_t =
    std::tuple<neighbor_span_t, delta_record_ptr_t, csr_page_t*>;

/**
 * @brief Main database class for Bw-Graph storage system
 */
class bw_graph_db_t {
public:
  /**
   * @brief Special page number reserved for giant vertices
   *
   * Giant vertices (high-degree vertices) are stored separately using this
   * page number as a marker for special handling.
   */
  static constexpr page_no_t GIANT_PAGE_NO = std::numeric_limits<page_no_t>::max();

  /**
   * @brief Vertex index for fast vertex-to-page mapping
   */
  vertex_index_t* vertex_index{nullptr};

  /**
   * @brief Disk manager for CSR page persistent storage
   */
  disk_manager_t* disk_manager{nullptr};

  /**
   * @brief Buffer pool for CSR page caching and memory management
   */
  buf_pool_t<csr_page_t>* buffer_pool{nullptr};

  /**
   * @brief Disk manager for delta page persistent storage
   */
  disk_manager_t* delta_disk_manager{nullptr};

  /**
   * @brief Buffer pool for delta page caching and memory management
   */
  buf_pool_t<delta_page_t>* delta_buffer_pool{nullptr};

  /**
   * @brief Separate database for giant vertices (high-degree vertices)
   */
  giant_vertex_db_t* giant_db{nullptr};

  /**
   * @brief LSM-Tree backed property storage for vertex and edge attributes.
   *
   * Stores arbitrary key-value properties per vertex and per edge using a
   * dedicated RocksDB instance.  Opened automatically by the constructor at
   * "<meta_prefix>/<graph_name>_propdb".
   */
  property_store_t* property_store{nullptr};

  /**
   * @brief SMO (Structure Modification Operation) control structure
   */
  smo_ctl_t* smo_ctl{nullptr};

  /**
   * @brief Background delta-page flusher.
   *
   * Periodically writes dirty delta pages to the delta disk manager.
   * Started after delta_buffer_pool and delta_disk_manager are ready.
   * Stopped (with a final flush_all) in the destructor.
   */
  std::unique_ptr<delta_flusher_t> delta_flusher_{nullptr};

  /**
   * @brief Background CSR-page flusher.
   *
   * Periodically writes dirty CSR pages (produced by SMO) to disk_manager.
   * Also woken explicitly by SMO via trigger_async_flush().
   */
  std::unique_ptr<csr_flusher_t> csr_flusher_{nullptr};

  /**
   * @brief Map of page numbers to index pages in L1 layer
   */
  folly::F14FastMap<page_no_t, index_page_t*> index_page_map;

  /**
   * @brief Root index page of the TAT hierarchy
   */
  index_page_t* root_index_page{nullptr};

  /**
   * @brief Number of levels in the TAT hierarchy (default: 2)
   */
  uint64_t level_count_{2};

  /**
   * @brief Page map table for tracking page metadata and consolidation status
   */
  page_map_t* page_map_table{nullptr};

#ifdef BW_GRAPH_ENABLE_TRANSACTION
  /**
   * @brief Transaction manager for MVCC-based transaction support
   */
  std::unique_ptr<txn_manager_t> txn_manager_{nullptr};
#endif // BW_GRAPH_ENABLE_TRANSACTION

  /**
   * @brief Sketch structure for tracking vertex updates
   */
  vertex_update_sketch_t* vertex_update_sketch_{nullptr};

  /**
   * @brief Name of the stored graph
   */
  std::string graph_name_;

  /**
   * @brief Approximate total edge count (both directions for undirected
   * graphs). Used by the adaptive edge_map threshold. Updated by
   * init_edge_count() and asynchronously maintained by insert_edge /
   * delete_edge.
   */
  std::atomic<uint64_t> total_edge_count_{0};

  /**
   * @brief Constructor for the graph database
   *
   * @param graph_name Name of the graph to load or create
   * @param rebuild Whether to rebuild the database from scratch
   * @param re_part Whether to re-partition the graph
   * @param compressed Whether to use compressed storage format
   * @param id_aware Whether to use ID-aware sequential storage
   * @param coarsening Whether to apply coarsening during partitioning
   * @param reordered Whether the graph should be reordered
   * @param manual_version_switch Whether SMO versions require explicit publication
   */
  bw_graph_db_t(const std::string& graph_name, bool rebuild = true, bool re_part = false,
                bool compressed = false, bool id_aware = false, bool coarsening = true,
                bool reordered = false, bool manual_version_switch = false);

  ~bw_graph_db_t();

  /**
   * @brief Open an existing graph database without rebuilding it.
   */
  static std::unique_ptr<bw_graph_db_t> open(const std::string& graph_name);

  /**
   * @brief Persist pending state and release all storage-engine resources.
   *
   * Safe to call more than once. The destructor calls close() automatically.
   */
  void close();

  /**
   * @brief Build the compressed database format
   *
   * Creates a space-efficient representation of the graph using compression
   * techniques on the CSR structure.
   */
  void build_compressed_db();

  /**
   * @brief Build TAT database with optional vertex reordering
   *
   * @param coarsening_weight Weight parameter for coarsening during
   * partitioning
   * @param reorder Whether to reorder vertices for better locality
   */
  void build_reorder_tat_db(uint64_t coarsening_weight, bool reorder = true);

  /**
   * @brief Build ID-aware sequential database
   */
  void build_seq_db();

#ifdef BW_GRAPH_ENABLE_TRANSACTION
  /**
   * @brief Initialize transaction manager for MVCC support
   *
   * @param initial_ts Initial timestamp value (default: 0)
   */
  void init_txn_manager(uint64_t initial_ts = 0);

  /**
   * @brief Begin a new transaction
   *
   * @param serializable Enable serializable isolation level (default: false)
   * @return Unique pointer to a new transaction
   */
  std::unique_ptr<txn_t> begin_txn(bool serializable = false);

  /**
   * @brief Get the transaction manager
   * @return Pointer to the transaction manager
   */
  txn_manager_t* get_txn_manager() { return txn_manager_.get(); }

  /**
   * @brief Check if transaction manager is initialized
   * @return true if initialized, false otherwise
   */
  bool has_txn_manager() const { return txn_manager_ != nullptr; }

  /**
   * @brief Insert an edge with MVCC timestamps (txn path only)
   */
  bool insert_edge_txn(v_id_t src, v_id_t dst, timestamp_t begin_ts, timestamp_t commit_ts);

  /**
   * @brief Delete an edge with MVCC timestamps (txn path only)
   */
  bool delete_edge_txn(v_id_t src, v_id_t dst, timestamp_t begin_ts, timestamp_t commit_ts);

  /**
   * @brief MVCC snapshot read: only returns neighbors committed at or before read_ts
   */
  std::vector<v_id_t> read_neighbor_clone_txn(v_id_t vertex_id, timestamp_t read_ts);
#endif // BW_GRAPH_ENABLE_TRANSACTION

  /**
   * @brief Insert a single vertex into the graph
   *
   * @param vertex_id The vertex ID to insert
   * @return true if the vertex was inserted successfully, false otherwise
   */
  bool insert_single_vertex(v_id_t vertex_id);

  /**
   * @brief Insert a batch of vertices with their neighbors
   *
   * @param vertex_batch Map from vertex ID to list of neighbor IDs
   * @return true if all vertices were inserted successfully, false otherwise
   */
  bool insert_vertex_batch(folly::F14FastMap<v_id_t, std::vector<v_id_t>>& vertex_batch);

  /**
   * @brief Insert a vertex with its neighbor list
   *
   * @param neighbors The neighbors of the new vertex
   * @return The new vertex ID assigned
   */
  v_id_t insert_vertex_with_neighbors(std::vector<v_id_t>& neighbors);

  /**
   * @brief Delete a vertex from the graph
   *
   * @param vertex_id The vertex ID to remove
   * @param remove_neighbors Whether to remove all edges to neighbors
   * @return true if the vertex was deleted successfully, false otherwise
   */
  bool delete_vertex(v_id_t vertex_id, bool remove_neighbors = false);

  /**
   * @brief Insert an edge into the graph
   *
   * @param src The source vertex ID
   * @param dst The destination vertex ID
   * @return true if the edge was inserted successfully, false otherwise
   */
  bool insert_edge(v_id_t src, v_id_t dst);

  /**
   * @brief Insert an edge directly into the buffer pool
   *
   * @param src The source vertex ID
   * @param dst The destination vertex ID
   * @return true if the edge was inserted successfully, false otherwise
   */
  bool insert_edge_direct(v_id_t src, v_id_t dst);

  /**
   * @brief Delete an edge from the graph
   *
   * @param src The source vertex ID
   * @param dst The destination vertex ID
   * @return true if the edge was deleted successfully, false otherwise
   */
  bool delete_edge(v_id_t src, v_id_t dst);

  /**
   * @brief Read the neighbors of a vertex (creates a copy)
   *
   * @param vertex_id The ID of the vertex
   * @return A vector of neighbor vertex IDs
   */
  std::vector<v_id_t> read_neighbor_clone(v_id_t vertex_id);

  /**
   * @brief Read the neighbors of a vertex from a cached page (zero-copy)
   *
   * @param vertex_id The ID of the vertex
   * @return A pair containing a span of neighbor vertex IDs and the CSR page
   * pointer
   */
  std::pair<neighbor_span_t, csr_page_t*> read_neighbor(v_id_t vertex_id);

  /**
   * @brief Read base neighbors and snapshot the current delta-chain head.
   *
   * The returned CSR page stays read-latched, matching read_neighbor(). The
   * delta pointer is only a snapshot of the current per-vertex chain head; the
   * caller can follow that record and its older successors without holding the
   * vertex latch.
   *
   * @param vertex_id The ID of the vertex
   * @return Base neighbor span, delta-head snapshot, and CSR page pointer
   */
  read_neighbor_with_delta_result_t read_neighbor_with_delta(v_id_t vertex_id);

  /**
   * @brief Read the neighbors of a vertex from a pre-cached page
   *
   * @param vertex_id The ID of the vertex
   * @param cached_page The cached page containing vertex data
   * @return A vector of neighbor vertex IDs
   */
  std::vector<v_id_t> read_neighbor_from_cached_page(v_id_t vertex_id,
                                                     std::shared_ptr<csr_page_t> cached_page);

  /**
   * @brief Get the degree (number of neighbors) of a vertex
   *
   * @param vertex_id The ID of the vertex
   * @return The degree of the vertex, 0 if vertex doesn't exist
   */
  uint64_t get_vertex_degree(v_id_t vertex_id);

  /**
   * @brief Read a CSR page by vertex ID from the database
   *
   * @param vertex_id The ID of the vertex
   * @return A pointer to the CSR page, or nullptr if not found
   */
  csr_page_t* read_page_vertex(v_id_t vertex_id);

  /**
   * @brief Perform consolidation of all pages based on the page map table
   *
   * Merges delta records into base pages to reduce lookup overhead.
   */
  void consolidate_all_pages();

  /**
   * @brief Wait for all pending consolidation operations to complete
   */
  void wait_for_pending_consolidations();

  /**
   * @brief Publish all SMO versions staged in manual version-switch mode.
   *
   * Callers must stop concurrent writers before invoking this method.
   */
  void force_switch_new_version();

  /**
   * @brief Synchronously flush all dirty delta pages to disk.
   *
   * Calls delta_flusher_->flush_all() if the flusher is active, otherwise
   * performs the flush inline.  Safe to call from any thread.
   *
   * @return Number of pages written.
   */
  size_t flush_delta_pages();

  /**
   * @brief Synchronously flush all dirty CSR pages to disk.
   *
   * Calls csr_flusher_->flush_all() if the flusher is active, otherwise
   * performs the flush inline. Safe to call from any thread.
   *
   * @return Number of pages written.
   */
  size_t flush_csr_pages();

  /**
   * @brief Perform breadth-first search (BFS) starting from a given vertex
   *
   * @param start_vertex The ID of the starting vertex
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint64_t>> bfs(v_id_t start_vertex);

  /**
   * @brief Perform parallel breadth-first search (BFS) starting from a given
   * vertex
   *
   * @param start_vertex The ID of the starting vertex
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint32_t>> parallel_bfs(v_id_t start_vertex);

  /**
   * @brief Compute BFS using the edge-map based parallel implementation
   *
   * @param start_vertex The ID of the starting vertex
   * @param threshold_divisor Sparse/dense switch divisor for edge_map
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint32_t>> parallel_bfs_map(v_id_t start_vertex,
                                                            long threshold_divisor = 20);

  /**
   * @brief Benchmark the scan-based parallel BFS implementation
   *
   * @param start_vertex The ID of the starting vertex
   * @param num_threads Number of worker threads to use (0 = auto)
   * @return Execution time in seconds
   */
  float benchmark_parallel_bfs_scan(v_id_t start_vertex, int num_threads = 0);

  /**
   * @brief Benchmark the edge-map based parallel BFS implementation
   *
   * @param start_vertex The ID of the starting vertex
   * @param threshold_divisor Sparse/dense switch divisor for edge_map
   * @param print_result Whether to print traversal statistics
   * @return Execution time in seconds
   */
  double benchmark_parallel_bfs_map(v_id_t start_vertex, long threshold_divisor = 20,
                                    bool print_result = true);

  /**
   * @brief Perform block-based breadth-first search (BFS) starting from a given
   * vertex
   *
   * @param start_vertex The ID of the starting vertex
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint64_t>> bfs_block(v_id_t start_vertex);

  /**
   * @brief Perform parallel block-based BFS starting from a given vertex
   *
   * @param start_vertex The ID of the starting vertex
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint64_t>> bfs_block_parallel(v_id_t start_vertex);

  /**
   * @brief Internal helper for block-based BFS within a single CSR page
   *
   * @param start_vertex The ID of the starting vertex
   * @param block The CSR page block to search within
   * @param outside A vector to store vertices found outside the block
   * @param visited A vector to keep track of visited vertices
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint64_t>> bfs_block_inner(v_id_t start_vertex, csr_page_t* block,
                                                           std::vector<v_id_t>& outside,
                                                           std::vector<bool>& visited);

  /**
   * @brief Parallel version of block-based BFS within a single CSR page
   *
   * @param start_vertex The ID of the starting vertex
   * @param block The CSR page block to search within
   * @param outside Concurrent vector to store vertices found outside the block
   * @param visited A vector to keep track of visited vertices
   * @param visited_mutex Mutex for protecting visited vector
   * @return A vector of pairs, each containing a vertex ID and its BFS level
   */
  std::vector<std::pair<v_id_t, uint64_t>>
  bfs_block_inner_parallel(v_id_t start_vertex, csr_page_t* block,
                           tbb::concurrent_vector<v_id_t>& outside, std::vector<bool>& visited,
                           std::mutex& visited_mutex);

  /**
   * @brief Process a page during parallel BFS traversal
   *
   * @param page_no The page number to process
   * @param page_vertices The vertices contained in the page
   * @param current_level The current BFS level
   * @param visited Concurrent bitmap tracking visited vertices
   * @param levels Array storing BFS levels for each vertex
   * @param next_frontier Concurrent vector to store next level's frontier
   * vertices
   */
  void process_page_bfs(page_no_t page_no, const std::vector<v_id_t>& page_vertices,
                        uint64_t current_level, concurrent_bit_map& visited,
                        std::unique_ptr<std::atomic<uint64_t>[]>& levels,
                        tbb::concurrent_vector<v_id_t>& next_frontier);

  /**
   * @brief Process the edges of a vertex during parallel BFS
   *
   * @param vertex_id The vertex ID to process
   * @param page The CSR page containing the vertex
   * @param current_level The current BFS level
   * @param visited Concurrent bitmap tracking visited vertices
   * @param levels Array storing BFS levels for each vertex
   * @param next_frontier Concurrent vector to store next level's frontier
   * vertices
   */
  void process_vertex_edges(v_id_t vertex_id, csr_page_t* page, uint64_t current_level,
                            concurrent_bit_map& visited,
                            std::unique_ptr<std::atomic<uint64_t>[]>& levels,
                            tbb::concurrent_vector<v_id_t>& next_frontier);

  /**
   * @brief Process giant vertices during parallel BFS
   *
   * @param giant_vertices Vector of giant vertex IDs to process
   * @param current_level The current BFS level
   * @param visited Concurrent bitmap tracking visited vertices
   * @param levels Array storing BFS levels for each vertex
   * @param next_frontier Concurrent vector to store next level's frontier
   * vertices
   */
  void process_giant_vertices(const std::vector<v_id_t>& giant_vertices, uint64_t current_level,
                              concurrent_bit_map& visited,
                              std::unique_ptr<std::atomic<uint64_t>[]>& levels,
                              tbb::concurrent_vector<v_id_t>& next_frontier);

  // Graph algorithms: PageRank.

  /**
   * @brief Compute PageRank using standard approach
   *
   * @param max_iterations Maximum number of iterations for PageRank computation
   * @param damping_factor Damping factor for PageRank algorithm (default: 0.85)
   * @param convergence_threshold Threshold for convergence checking (default:
   * 1e-6)
   * @return A vector of pairs, each containing a vertex ID and its PageRank
   * value
   */
  std::vector<std::pair<v_id_t, double>> pagerank(uint64_t max_iterations = 20,
                                                  double damping_factor = 0.85,
                                                  double convergence_threshold = 1e-6);

  /**
   * @brief Compute PageRank using parallel processing
   *
   * @param max_iterations Maximum number of iterations for PageRank computation
   * @param damping_factor Damping factor for PageRank algorithm (default: 0.85)
   * @param convergence_threshold Threshold for convergence checking (default:
   * 1e-6)
   * @return A vector of pairs, each containing a vertex ID and its PageRank
   * value
   */
  std::vector<std::pair<v_id_t, float>> parallel_pagerank(uint64_t max_iterations = 20,
                                                          float damping_factor = 0.85,
                                                          float convergence_threshold = 1e-6);

  /**
   * @brief Compute PageRank using the edge-map based parallel implementation
   *
   * @param max_iterations Maximum number of iterations
   * @param damping_factor PageRank damping factor
   * @param convergence_threshold Convergence threshold for early stopping
   * @return A vector of pairs, each containing a vertex ID and its PageRank
   * value
   */
  std::vector<std::pair<v_id_t, double>> parallel_pagerank_map(uint64_t max_iterations = 20,
                                                               double damping_factor = 0.85,
                                                               double convergence_threshold = 1e-6);

  /**
   * @brief Benchmark the scan-based parallel PageRank implementation
   *
   * @param max_iterations Maximum number of iterations
   * @param damping_factor PageRank damping factor
   * @param convergence_threshold Convergence threshold for early stopping
   * @param num_threads Number of worker threads to use (0 = auto)
   * @return Execution time in seconds
   */
  float benchmark_parallel_pagerank_scan(uint64_t max_iterations = 20, float damping_factor = 0.85,
                                         float convergence_threshold = 1e-6, int num_threads = 0);

  /**
   * @brief Benchmark the edge-map based parallel PageRank implementation
   *
   * @param max_iterations Maximum number of iterations
   * @param damping_factor PageRank damping factor
   * @param convergence_threshold Convergence threshold for early stopping
   * @param print_result Whether to print iteration statistics
   * @return Execution time in seconds
   */
  double benchmark_parallel_pagerank_map(uint64_t max_iterations = 10, double damping_factor = 0.85,
                                         double convergence_threshold = 1e-7,
                                         bool print_result = true);

  /**
   * @brief Process a page for PageRank computation
   *
   * @param page_no The page number to process
   * @param page_vertices The vertices contained in the page
   * @param rank_current Current PageRank values for each vertex
   * @param rank_next Next PageRank values for each vertex
   */
  void process_page_pagerank(page_no_t page_no, const std::vector<v_id_t>& page_vertices,
                             std::unique_ptr<std::atomic<double>[]>& rank_current,
                             std::unique_ptr<std::atomic<double>[]>& rank_next);

  /**
   * @brief Process a single vertex for PageRank computation
   *
   * @param vertex_id The ID of the vertex
   * @param page The CSR page containing the vertex
   * @param rank_current Current PageRank values for each vertex
   * @param rank_next Next PageRank values for each vertex
   */
  void process_vertex_pagerank(v_id_t vertex_id, csr_page_t* page,
                               std::unique_ptr<std::atomic<double>[]>& rank_current,
                               std::unique_ptr<std::atomic<double>[]>& rank_next);

  /**
   * @brief Process giant vertices for PageRank computation
   *
   * @param giant_vertices Vector of giant vertex IDs to process
   * @param rank_current Current PageRank values for each vertex
   * @param rank_next Next PageRank values for each vertex
   */
  void process_giant_vertices_pagerank(const std::vector<v_id_t>& giant_vertices,
                                       std::unique_ptr<std::atomic<double>[]>& rank_current,
                                       std::unique_ptr<std::atomic<double>[]>& rank_next);

  /**
   * @brief Compute WCC (Weakly Connected Components) using edge scan
   *
   * @return A vector of pairs, each containing a vertex ID and its component ID
   */
  std::vector<std::pair<v_id_t, v_id_t>> wcc();

  /**
   * @brief Compute WCC using parallel edge scan
   *
   * @return A vector of pairs, each containing a vertex ID and its component ID
   */
  std::vector<std::pair<v_id_t, v_id_t>> parallel_wcc();

  /**
   * @brief Compute WCC using Shiloach-Vishkin over edge_map
   *
   * @param threshold_divisor Sparse/dense switch divisor for edge_map
   * @return A vector of pairs, each containing a vertex ID and its component ID
   */
  std::vector<std::pair<v_id_t, v_id_t>> wcc_sv(long threshold_divisor = 20);

  /**
   * @brief Compute WCC using min-label propagation over edge_map
   *
   * @param threshold_divisor Sparse/dense switch divisor for edge_map
   * @return A vector of pairs, each containing a vertex ID and its component ID
   */
  std::vector<std::pair<v_id_t, v_id_t>> wcc_map(long threshold_divisor = 20);

  float benchmark_parallel_wcc_scan(int num_threads = 0);
  double benchmark_wcc_sv(long threshold_divisor = 20, bool print_result = true);

  /**
   * @brief Benchmark Ligra-style min-label WCC via edge_map.
   *
   * Propagates minimum vertex-ID labels across edges until no label changes.
   * Equivalent to the Ligra CC algorithm (Components.C).
   *
   * @param threshold_divisor Sparse/dense switch divisor for edge_map
   * @param print_result      Whether to print component statistics
   * @return Execution time in seconds
   */
  double benchmark_wcc_map(long threshold_divisor = 20, bool print_result = true);

  /**
   * @brief Process a page for the WCC algorithm
   *
   * @param page_no The ID of the page to process
   * @param page_vertices The vertices in the page
   * @param components Array to store the WCC component IDs
   * @param changed Flag to indicate if any changes were made
   */
  void process_page_wcc(page_no_t page_no, const std::vector<v_id_t>& page_vertices,
                        std::unique_ptr<std::atomic<v_id_t>[]>& components,
                        std::atomic<bool>& changed);

  /**
   * @brief Process edges for a single vertex in WCC
   *
   * @param vertex_id The ID of the vertex to process
   * @param page The CSR page containing the vertex
   * @param components Array to store the WCC component IDs
   * @param changed Flag to indicate if any changes were made
   */
  void process_vertex_wcc(v_id_t vertex_id, csr_page_t* page,
                          std::unique_ptr<std::atomic<v_id_t>[]>& components,
                          std::atomic<bool>& changed);

  /**
   * @brief Process giant vertices for WCC
   *
   * @param giant_vertices A vector of giant vertex IDs to process
   * @param components Array to store the WCC component IDs
   * @param changed Flag to indicate if any changes were made
   */
  void process_giant_vertices_wcc(const std::vector<v_id_t>& giant_vertices,
                                  std::unique_ptr<std::atomic<v_id_t>[]>& components,
                                  std::atomic<bool>& changed);

  /**
   * @brief Perform Community Detection using Label Propagation (CDLP)
   * algorithm
   *
   * @param max_iterations Maximum number of iterations for CDLP (default:
   * 100)
   * @param use_random_order Whether to use random order for vertex updates
   * @return A vector of pairs, each containing a vertex ID and its
   * community label
   */
  std::vector<std::pair<v_id_t, v_id_t>> cdlp(uint64_t max_iterations = 100,
                                              bool use_random_order = true);

  /**
   * @brief Perform Community Detection using parallel Label Propagation
   *
   * @param max_iterations Maximum number of iterations for CDLP (default: 100)
   * @return A vector of pairs, each containing a vertex ID and its community
   * label
   */
  /**
   * @brief Perform Community Detection using scan-based parallel Label
   * Propagation
   *
   * @param max_iterations Maximum number of iterations for CDLP
   * @return A vector of pairs, each containing a vertex ID and its community
   * label
   */
  std::vector<std::pair<v_id_t, v_id_t>> parallel_cdlp(uint64_t max_iterations = 100);

  /**
   * @brief Compute CDLP using the edge-map based parallel implementation
   *
   * @param max_iterations Maximum number of iterations for CDLP
   * @return A vector of pairs, each containing a vertex ID and its community
   * label
   */
  std::vector<std::pair<v_id_t, v_id_t>> parallel_cdlp_map(uint64_t max_iterations = 20);

  /**
   * @brief Compute voting-based CDLP with pull-mode hash-map vote counting
   *
   * @param max_iterations Maximum number of label-propagation rounds
   * @return A vector of pairs, each containing a vertex ID and its community
   * label
   */
  std::vector<std::pair<v_id_t, v_id_t>> cdlp_voting_map(uint64_t max_iterations = 20);

  /**
   * @brief Benchmark the scan-based parallel CDLP implementation
   *
   * @param max_iterations Maximum number of iterations for CDLP
   * @param num_threads Number of worker threads to use (0 = auto)
   * @return Execution time in seconds
   */
  float benchmark_parallel_cdlp_scan(uint64_t max_iterations = 100, int num_threads = 0);

  /**
   * @brief Benchmark the edge-map based parallel CDLP implementation
   *
   * @param max_iterations Maximum number of iterations for CDLP
   * @param print_result Whether to print iteration statistics
   * @return Execution time in seconds
   */
  double benchmark_parallel_cdlp_map(uint64_t max_iterations = 20, bool print_result = true);

  /**
   * @brief Benchmark voting-based CDLP: pull model with hash-map vote counting.
   *
   * Each vertex independently reads its neighbours' current labels, counts
   * frequencies in a thread-local hash map, and picks the most voted label
   * (ties broken by lowest label ID).  Unlike benchmark_parallel_cdlp_map
   * there is no fixed-slot overflow.
   *
   * @param max_iterations Maximum number of label-propagation rounds
   * @param print_result   Whether to print per-iteration statistics
   * @return Execution time in seconds
   */
  double benchmark_cdlp_voting_map(uint64_t max_iterations = 20, bool print_result = true);

  /**
   * @brief Process a page for the CDLP algorithm
   *
   * @param page_no The ID of the page to process
   * @param page_vertices The vertices in the page
   * @param labels Array to store the CDLP community labels
   * @param changed Flag to indicate if any changes were made
   */
  void process_page_cdlp(page_no_t page_no, const std::vector<v_id_t>& page_vertices,
                         std::unique_ptr<std::atomic<v_id_t>[]>& labels,
                         std::atomic<bool>& changed);

  /**
   * @brief Process a single vertex for CDLP computation
   *
   * @param vertex_id The ID of the vertex to process
   * @param page The CSR page containing the vertex
   * @param labels Array to store the CDLP community labels
   * @param changed Flag to indicate if any changes were made
   */
  void process_vertex_cdlp(v_id_t vertex_id, csr_page_t* page,
                           std::unique_ptr<std::atomic<v_id_t>[]>& labels,
                           std::atomic<bool>& changed);

  /**
   * @brief Process giant vertices for CDLP computation
   *
   * @param giant_vertices A vector of giant vertex IDs to process
   * @param labels Array to store the CDLP community labels
   * @param changed Flag to indicate if any changes were made
   */
  void process_giant_vertices_cdlp(const std::vector<v_id_t>& giant_vertices,
                                   std::unique_ptr<std::atomic<v_id_t>[]>& labels,
                                   std::atomic<bool>& changed);

  /**
   * @brief Find the most frequent label in a label count map (thread-safe
   * version)
   *
   * @param label_count A map of labels to their counts
   * @return The label with the highest count
   */
  v_id_t find_most_frequent_label_atomic(const folly::F14FastMap<v_id_t, uint64_t>& label_count);

  /**
   * @brief Find the most frequent label in a label count map
   *
   * @param label_count A map of labels to their counts
   * @return The label with the highest count
   */
  v_id_t find_most_frequent_label(const std::unordered_map<v_id_t, uint64_t>& label_count);

  void process_giant_vertices_cdlp_optimized(const std::vector<v_id_t>& giant_vertices,
                                             std::unique_ptr<std::atomic<v_id_t>[]>& labels,
                                             std::atomic<bool>& changed,
                                             std::vector<uint64_t>& label_count,
                                             std::vector<v_id_t>& touched_labels);

  void process_page_cdlp_optimized(page_no_t page_no, const std::vector<v_id_t>& page_vertices,
                                   std::unique_ptr<std::atomic<v_id_t>[]>& labels,
                                   std::atomic<bool>& changed, std::vector<uint64_t>& label_count,
                                   std::vector<v_id_t>& touched_labels);

  void process_vertex_cdlp_optimized(v_id_t vertex_id, csr_page_t* page,
                                     std::unique_ptr<std::atomic<v_id_t>[]>& labels,
                                     std::atomic<bool>& changed, std::vector<uint64_t>& label_count,
                                     std::vector<v_id_t>& touched_labels);

  /**
   * @brief Sample a subgraph from the graph using page-based sampling
   *
   * @param start_vertex The ID of the starting vertex
   * @return A map of vertex IDs to their sampled neighbors
   */
  std::shared_ptr<mem_sub_map_t> graph_sample_page(v_id_t start_vertex);

  /**
   * @brief Sample a subgraph from the graph using random walk
   *
   * @param start_vertex The ID of the starting vertex
   * @param max_vertexs The maximum number of vertices to sample (default: 200)
   * @return A map of vertex IDs to their sampled neighbors
   */
  std::shared_ptr<mem_sub_map_t> graph_sample_walk(v_id_t start_vertex, uint64_t max_vertexs = 200);

  /**
   * @brief Get the total count of vertices in the graph
   *
   * @return The number of vertices
   */
  uint32_t get_vertex_count() const;

  /**
   * @brief Return the cached total edge count (approximate, both directions).
   * Call init_edge_count() once after build to initialise the counter.
   */
  uint64_t get_total_edge_count() const {
    return total_edge_count_.load(std::memory_order_relaxed);
  }

  /**
   * @brief Scan all CSR pages to compute the exact total edge count and cache
   * it in total_edge_count_. Should be called once after the database is built
   * and before running graph algorithms that use adaptive edge_map.
   */
  void init_edge_count();

  /**
   * @brief Compute degree distribution of the graph
   *
   * @param step The step size for grouping degrees (default: 10)
   * @return A vector of pairs where each pair contains (degree_range_start,
   * percentage)
   *
   * This method computes the degree distribution by grouping vertices into
   * degree ranges. For example, with step=10, it returns percentages for
   * degrees [0-9], [10-19], [20-29], etc. The percentage indicates what
   * fraction of vertices fall into each degree range.
   */
  std::vector<std::pair<uint64_t, double>> compute_degree_distribution(uint64_t step = 10);

  /**
   * @brief Warm up the database by pre-loading vertices into cache
   *
   * This can improve query performance by bringing frequently accessed data
   * into memory before actual queries begin.
   */
  void warm_up();

  /**
   * @brief Build a Topology-Aware Tree (TAT) from a collection of CSR pages
   *
   * This function constructs a hierarchical index structure over the given CSR
   * pages by iteratively building multiple levels of index pages until reaching
   * a single root. The process involves:
   * 1. Computing block adjacency relationships from vertex neighbors
   * 2. Partitioning blocks and building index pages level by level
   * 3. Maintaining parent pointers and sampled neighbor lists for locality
   *
   * @param pages Vector of CSR page pointers to build the TAT from (L0 base
   * pages)
   * @param start_page_no Starting page number for allocating new index pages
   * @param vertex_index Vertex location index for looking up neighbor page
   * locations
   * @param com_graph Compressed graph for accessing vertex neighbor lists
   * @return tat_build_result_t Structure containing root page, level count, and
   * all index pages
   */
  tat_build_result_t build_tat_from_csr_pages(std::vector<csr_page_t*>& pages,
                                              page_no_t start_page_no, vertex_index_t* vertex_index,
                                              mem_sub_com_t& com_graph);

  /**
   * @brief Build a Topology-Aware Tree from a list of index pages
   *
   * This merges multiple small TATs (each with its own root) into a larger TAT.
   * Used when building hierarchical structures over already-built index pages.
   *
   * @param root_pages List of root index pages from small TATs
   * @param start_page_no Starting page number for allocating new index pages
   * @return tat_build_result_t Structure containing merged root page and
   * metadata
   */
  tat_build_result_t build_tat_from_index_pages(std::vector<index_page_t*>& root_pages,
                                                page_no_t start_page_no);

  /**
   * @brief Create a JSON representation of the database
   *
   * Exports database metadata and structure to JSON format for debugging
   * or external analysis.
   */
  void create_db_json();

  /**
   * @brief Save index pages to a binary file with buffered I/O
   *
   * @param file_path The path to the file where index pages will be saved
   * @param buffer_size The size of the I/O buffer (default: 1MB)
   * @return true if save is successful, false otherwise
   */
  bool save_index_pages_to_file(const std::string& file_path, size_t buffer_size = 1024 * 1024);

  /**
   * @brief Load index pages from a binary file with buffered I/O
   *
   * @param file_path The path to the file from which index pages will be loaded
   * @param buffer_size The size of the I/O buffer (default: 1MB)
   * @return true if load is successful, false otherwise
   */
  bool load_index_pages_from_file(const std::string& file_path, size_t buffer_size = 1024 * 1024);

  // ── Property management API ───────────────────────────────────────────────
  //
  // These methods forward directly to property_store.  The store is always
  // initialized by the constructor, so callers need no knowledge of the
  // underlying RocksDB path.

  /**
   * @brief Write (insert or overwrite) a single vertex property.
   */
  bool set_vertex_property(v_id_t vertex_id, const std::string& prop_key,
                           const std::string& prop_value);

  /**
   * @brief Read a single vertex property.
   * @return The value, or std::nullopt if not found.
   */
  std::optional<std::string> get_vertex_property(v_id_t vertex_id, const std::string& prop_key);

  /**
   * @brief Delete a single vertex property.
   */
  bool delete_vertex_property(v_id_t vertex_id, const std::string& prop_key);

  /**
   * @brief Retrieve all properties of a vertex.
   * @return Map from property name to value.
   */
  std::unordered_map<std::string, std::string> get_all_vertex_properties(v_id_t vertex_id);

  /**
   * @brief Delete all properties of a vertex.
   */
  bool delete_all_vertex_properties(v_id_t vertex_id);

  /**
   * @brief Write multiple vertex properties atomically.
   */
  bool set_vertex_properties(v_id_t vertex_id,
                             const std::unordered_map<std::string, std::string>& properties);

  /**
   * @brief Write (insert or overwrite) a single edge property.
   */
  bool set_edge_property(v_id_t src_id, v_id_t dst_id, const std::string& prop_key,
                         const std::string& prop_value);

  /**
   * @brief Read a single edge property.
   * @return The value, or std::nullopt if not found.
   */
  std::optional<std::string> get_edge_property(v_id_t src_id, v_id_t dst_id,
                                               const std::string& prop_key);

  /**
   * @brief Delete a single edge property.
   */
  bool delete_edge_property(v_id_t src_id, v_id_t dst_id, const std::string& prop_key);

  /**
   * @brief Retrieve all properties of an edge.
   * @return Map from property name to value.
   */
  std::unordered_map<std::string, std::string> get_all_edge_properties(v_id_t src_id,
                                                                       v_id_t dst_id);

  /**
   * @brief Delete all properties of an edge.
   */
  bool delete_all_edge_properties(v_id_t src_id, v_id_t dst_id);

  /**
   * @brief Write multiple edge properties atomically.
   */
  bool set_edge_properties(v_id_t src_id, v_id_t dst_id,
                           const std::unordered_map<std::string, std::string>& properties);

private:
  /**
   * @brief Build standard database with optional partitioning
   *
   * @param re_part Whether to recompute partitioning
   */
  void build_standard_db(bool re_part);

  /**
   * @brief Build TAT hierarchy from CSR pages
   *
   * @param page_list List of CSR pages to build TAT from
   * @param com_graph The compact graph representation
   */
  void build_tat_hierarchy(std::vector<csr_page_t*>& page_list, mem_sub_com_t& com_graph);

  /**
   * @brief Rebuild TAT structure from disk
   *
   * Called when vertex index exists but index pages don't.
   * Reconstructs the TAT from existing CSR pages on disk.
   */
  void rebuild_tat_from_disk();

  /**
   * @brief Reconstruct page list from vertex index
   *
   * @param page_list Output page list to populate
   * @param com_graph The compact graph representation
   */
  void reconstruct_page_list_from_index(std::vector<csr_page_t*>& page_list);

  /**
   * @brief Load or compute graph partition
   *
   * @param com_graph The compact graph representation
   * @param graph_name Graph name for loading/saving partition
   * @param re_part Whether to recompute partitioning even if cached
   * @return The graph partition result
   */
  graph_partition_t load_or_compute_partition(mem_sub_com_t& com_graph,
                                              const std::string& graph_name, bool re_part);

  /**
   * @brief Load partition from input stream
   *
   * @param in Input file stream to read from
   * @param partition Output partition structure to populate
   * @return true if loaded successfully, false otherwise
   */
  bool load_partition_from_stream(std::ifstream& in, graph_partition_t& partition);

  /**
   * @brief Save partition to file
   *
   * @param partition The partition to save
   * @param graph_name Graph name for file path construction
   */
  void save_partition_to_file(const graph_partition_t& partition, const std::string& graph_name);

  /**
   * @brief Try to load vertex index from file
   *
   * @param graph_name Graph name for file path construction
   * @return true if loaded successfully, false otherwise
   */
  bool try_load_vertex_index(const std::string& graph_name);

  /**
   * @brief Try to load index pages from file
   *
   * @param graph_name Graph name for file path construction
   * @return true if loaded successfully, false otherwise
   */
  bool try_load_index_pages(const std::string& graph_name);

  /**
   * @brief Save vertex index to file
   *
   * @param graph_name Graph name for file path construction
   */
  void save_vertex_index(const std::string& graph_name);

  /**
   * @brief Save index pages to file
   *
   * @param graph_name Graph name for file path construction
   */
  void save_index_pages(const std::string& graph_name);

private:
  bool closed_{false};
};

#endif // BW_GRAPH_DB_DB_H
